// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2mwvQomZClWY06DTgKHdDgxFSE9rw6c',
    appId: '1:512757128265:web:bb978e7337576e5f263398',
    messagingSenderId: '512757128265',
    projectId: 'sustaio-2d6e6',
    authDomain: 'sustaio-2d6e6.firebaseapp.com',
    storageBucket: 'sustaio-2d6e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAusGvwjhj3ohrjzYaq3PeSVj1Q6RpCuT0',
    appId: '1:512757128265:android:f1f9c299ddaf50c0263398',
    messagingSenderId: '512757128265',
    projectId: 'sustaio-2d6e6',
    storageBucket: 'sustaio-2d6e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-XL_FeVxVDMztcGlUrcWSezcHWJC73iQ',
    appId: '1:512757128265:ios:a86995e387261359263398',
    messagingSenderId: '512757128265',
    projectId: 'sustaio-2d6e6',
    storageBucket: 'sustaio-2d6e6.appspot.com',
    iosBundleId: 'com.example.gdsc2024',
  );
}
